### ISSUE TITLE
How can i generate eigenvector 

### ISSUE THREAD

**Issue by fredcool112** [eigenkernel/eigenkernel#1]
I try to generate the eigenvector by typing this:

mpirun -np 4 bin/eigbench -s  scalapack -d vector/ -l timw.dat  matrix/ELSES_MATRIX_VCNT400std_A.mtx

However it does not happen anything related to eigenvectors.

**Comment by LennMars** [comment]
Thank you for your report.

You need to specify an index range of eigenvectors to be output by `-p` option.
For example, please try the following command.
`mpirun -np 4 bin/eigbench -s scalapack -d vector/ -l timw.dat -p 1-400 matrix/ELSES_MATRIX_VCNT400std_A.mtx`

Also note that the directory `vector/` must be created before execution.

**Comment by takeohoshi** [comment]
Thank you for your report and comment.
I added the explanation for generating eigenvectors to Quick Start of readme.md

**Comment by fredcool112** [comment]
Thank you! 
Another issue is that Why there is not imaginary number existing inside the eigenvector ?

**Comment by takeohoshi** [comment]
> Why there is not imaginary number existing inside the eigenvector ?

The present code supports only the real-symmetric matrix problems and the calculated eigenvalue and eigenvectors do not have imaginary part.
